### PR TITLE
Add an option to output a JS object

### PR DESCRIPTION
**Pull request by yciabaud**
When dealing with internationalization, it could be handy to have the number and the unit separately to apply local number format and translate units.

What do you think?

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't like options that completely changes the return value. Usually it should be a separate method then. I'm gonna pass on this though as it's simpler to just split on a space. No option needed.

```js
const [num, unit] = prettyBytes(1337).split(' ');
```

**Comment by yciabaud** [comment]
Well it is true except that the number is preformatted.

**Comment by sindresorhus** [comment]
I see your point, but I don't want to complicate the API for something I would never personally use. If you think this is important you could always just fork and publish it as a separate more flexible module. I would be totally fine with that ;)

**Comment by yciabaud** [comment]
Yeah in fact I dont need this neither, splitting the string should be fine.

Thank you for your feedback.

Le mer. 24 août 2016 21:38, Sindre Sorhus <notifications@github.com> a
écrit :

**Pull request closed without merging**
